### ISSUE TITLE
Invalid byte sequence in utf-8

### ISSUE THREAD

**Issue by xidiandb** [fluent/fluent-plugin-prometheus#116]
when i `curl host:port/metrics`, show that `invalid byte sequence in UTF-8`
and the node will down
Chinese may appear in the log

**Comment by xidiandb** [comment]
日志中可能出现中文
Chinese may appear in the log

**Comment by ganmacs** [comment]
Right. if `label` includes invalid utf-8 chars, prometheus-client seems to raise an error at [here](https://github.com/prometheus/client_ruby/blob/v0.9.0/lib/prometheus/client/formats/text.rb#L91).

https://github.com/kataring/fluent-plugin-string-scrub may be helpful to solve this issue.

**Comment by xidiandb** [comment]
it works! Thanks @ganmacs

**Comment by xidiandb** [comment]
@ganmacs  Do you know of any plugins that delete records that contain invalid utf-8 chars
