### ISSUE TITLE
Allow environment variables in labels

### ISSUE THREAD

**Issue by dawidrabiega** [fluent/fluent-plugin-prometheus#128]
Hey,
I need to pass value of environment variable to label value. In my case it's nodeName defined as:

        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName

I would use it in source:

    <source>
      @type prometheus_monitor
      <labels>
        node #{ENV['NODE_NAME']}
      </labels>
    </source>

Currently it seems, that it's not expanded.

**Comment by repeatedly** [comment]
Wrap the parameter with `"`.
See official document: https://docs.fluentd.org/configuration/config-file#embedded-ruby-code

**Comment by dawidrabiega** [comment]
Thanks, It works like a harm!

Correct version:

    <source>
      @type prometheus_monitor
      <labels>
        node "#{ENV['NODE_NAME']}"
      </labels>
    </source>

**Comment by ganmacs** [comment]
I'm closing this issue. feel free to ask any questions.
