### ISSUE TITLE
Method name typo for ExpandBuilder

### ISSUE THREAD

**Issue by terciodemelo** [fluent/fluent-plugin-prometheus#140]
This is written `buidl` instead of `build`

https://github.com/fluent/fluent-plugin-prometheus/blame/790a87d66bee29b945e5e6f8425b7c8fe2ce09f7/lib/fluent/plugin/in_prometheus_output_monitor.rb#L47

**Comment by ganmacs** [comment]
https://github.com/fluent/fluent-plugin-prometheus/pull/142
