### ISSUE TITLE
undefined method `buidl'

### ISSUE THREAD

**Issue by romanvog** [fluent/fluent-plugin-prometheus#141]
fluentd pod fails to launch due to what seems to be a typo

/fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-prometheus-1.7.1/lib/fluent/plugin/in_prometheus_output_monitor.rb:47:in `configure': undefined method `buidl' for #<Fluent::Plugin::Prometheus::ExpandBuilder:0x007faa3f7559e0> (NoMethodError)

**Comment by repeatedly** [comment]
Just released v1.7.2 with this fix.
