### ISSUE TITLE
Please bind on IPv4 & IPv6 by default

### ISSUE THREAD

**Issue by stv0g** [fluent/fluent-plugin-prometheus#151]
Can we replace the following default argument `0.0.0.0` by `::`?

https://github.com/fluent/fluent-plugin-prometheus/blob/b27de0a17093815107293575671835f72467786f/lib/fluent/plugin/in_prometheus.rb#L13

**Comment by ganmacs** [comment]
I don't think so. Is there any reasonable reason we should change?

**Comment by stv0g** [comment]
Yes definitly. We should encourage everybody to deploy their new services and network via IPv6.

Such small changes make it easier. We should treat them equal at least. Why listen on IPv4 by default only?

https://www.worldipv6launch.org/

**Comment by stv0g** [comment]
Btw. I am not saying that we should not listen on IPv4 anymore. Replacing `0.0.0.0` with `::` will cause the socket to listen on IPv4 **and** IPv6

**Comment by ganmacs** [comment]
It's breaking change. if users already use the address in ipv6, they get something port conflict error because this plugin starts to listen to a new port. So we have to avoid it as much as possible.

**Comment by stv0g** [comment]
Alright, I will close the PR.

Sad to see that all new IPv6 users will fall in the same pitfall as me.

**Comment by NoctivagusObitus** [comment]
Quite some time ago by now but I like to mention falling in exactly that pitfall.
