### ISSUE TITLE
Metrics endpoint limited to 5 incoming connections. 

### ISSUE THREAD

**Issue by AlexHockey** [fluent/fluent-plugin-prometheus#156]
It appears that the fluentd only allows 5 concurrent connections to the metrics endpoint. Prometheus uses persistent connections, so this means that a single fluentd instance can only be monitored by 5 Prometheus instances. 

This is unlikely to be an issue in production, but I just ran into it on a test system and it caught me by surprise. Is it worth documenting this somewhere, or producing a log when this happens?

**Comment by repeatedly** [comment]
We forgot to release v1.8.0 to avoid this webrick issue.

https://github.com/fluent/fluent-plugin-prometheus#requirements

v1.8.0 and `async-http` combo fixes this problem.

**Comment by AlexHockey** [comment]
Thanks very much, I'll give that a go.
