### ISSUE TITLE
What's plugin_id? how to get rid of it

### ISSUE THREAD

**Issue by flaker** [fluent/fluent-plugin-prometheus#177]
Hi!

I am using fluentd receiving logs from multiple fluent-bit instances. I think it's a common scenario. While querying fluentd I see the following results:

```
fluentd_output_status_buffer_available_space_ratio{endpoint="fluentd-metrics", hostname="fluentd-aggregator-useast2-c1-us-east-2b-0", instance="172.16.171.158:24231", job="fluentd-aggregator-us-east-2b", namespace="default", plugin_id="object:1920508", pod="fluentd-aggregator-useast2-c1-us-east-2b-0", service="fluentd-aggregator-us-east-2b", type="s3", worker_id="0"}
fluentd_output_status_buffer_available_space_ratio{endpoint="fluentd-metrics", hostname="fluentd-aggregator-useast2-c1-us-east-2b-0", instance="172.16.171.158:24231", job="fluentd-aggregator-us-east-2b", namespace="default", plugin_id="object:1c73048", pod="fluentd-aggregator-useast2-c1-us-east-2b-0", service="fluentd-aggregator-us-east-2b", type="s3", worker_id="0"}
```
they are the same fluentd instance but they differ in "plugin_id". Is there any way to make it more useful for a query? it's current value (`object:xxxxxxxx`) is not useful as it is.

The docs I could find only mention this label for the `in_tail` plugin that I am not explicitly using since I only receive using `forward`.

Thank you!

**Comment by dimitarKiryakov** [comment]
@flaker Did you manage to find a way?

**Comment by LHozzan** [comment]
Same question here.
