### ISSUE TITLE
Add fluentd input count metrics

### ISSUE THREAD

**Issue by aslafy-z** [fluent/fluent-plugin-prometheus#199]
I could not find any metric that shows how much records fluentd was receiving.
Am I missing something?

**Comment by avivgold098** [comment]
Can use this example - with filter of `**` to count incoming data 
https://docs.fluentd.org/monitoring-fluentd/monitoring-prometheus#step-1-counting-incoming-records-by-prometheus-filter-plugin

**Comment by Athishpranav2003** [comment]
@aslafy-z i guess what @avivgold098 mentioned is correct. Could you close this issue ?

**Comment by aslafy-z** [comment]
Thank you @avivgold098 @Athishpranav2003
