### ISSUE TITLE
Information about "fluentd_output_status_emit_count" metric

### ISSUE THREAD

**Issue by dannyk81** [fluent/fluent-plugin-prometheus#34]
Hey!

Thanks for this great plugin, we find it very useful!

I'm trying to understand what exactly `fluentd_output_status_emit_count` is measuring, I can't seem to find any documentation that describes it and when I curl the fluentd monitoring agent - I don't see it there at all.

Can you please provide some details about this.

Also, since this seem to be a counter - any reason it is defined as a gauge?

**Comment by kazegusuri** [comment]
`fluentd_output_status_emit_count` represents the number of (trying to) emits in the plugin.
More specificly, the number of calls of `Fluent::BufferedOutput#emit` (at least for v0.12)




> Also, since this seem to be a counter - any reason it is defined as a gauge?

The metric is instrumented by Fluentd itself, not this plugin, and exposed via in_monitor_agent plugin, so this plugin exposes the values asis as guage.
Are there any problems exposing the metric as gauge? If there are, I will reconsider it.

**Comment by dannyk81** [comment]
Thanks for the details! so if I understand correctly, this represent the amount of buffer flushes in the measured period.

Regarding Gauge/Counter - I don't see a specific issue at the moment, however since this is essentially a counter I would like to use a `rate` function on it in Prometheus - this works even if it's a gauge, but we need to make sure that the values always goes up (or reset when the process restarts) otherwise rate will provide bad answers.
