### ISSUE TITLE
Transfer into fluent organization with license change

### ISSUE THREAD

**Issue by kazegusuri** [fluent/fluent-plugin-prometheus#36]
I have a plan to transfer this repository into [fluent](https://github.com/fluent) orgnization for better user support.
We need to change license of this repository to Apache License v 2.0 before that.
If no one has objections, I will change license around next week.

**Comment by repeatedly** [comment]
Go fluent org repository?

**Comment by kazegusuri** [comment]
@repeatedly yes, time to transfer.

**Comment by kazegusuri** [comment]
done!
