### ISSUE TITLE
out-prometheus doesn't refresh gauge if no receive record for a while

### ISSUE THREAD

**Issue by vinkdong** [fluent/fluent-plugin-prometheus#37]
Hi, There is my environment:
fluentd: `fluentd-0.12.40`
fluent-plugin-prometheus: `0.3.0`

My fluentd conf like : 
```xml
  <source>
    @type prometheus
  </source>
  <source>
    @type tail
    path /a.log
    pos_file /a.pos
    tag a.log
    format /^(?<count>\d+)$/
    types count:integer
  </source>
  <match a.log>
    @type prometheus
    <metric>
      name message_warn_counter
      type gauge
      desc The total number of count in message in 10s.
      key count
    </metric>
  </match>
```

When I exec `echo 15 >> a.log` it got `message_warn_counter 15.0` is correct but if I wait for 1 min and exec `curl http://localhost:24231/metrics` again still get `message_warn_counter 15.0`, I think that show absent or 0, isn't it?

**Comment by kazegusuri** [comment]
In my understanding, gauge represents current value asis. So it should be `15.0`.

**Comment by kazegusuri** [comment]
oh, my misunderstanding. This is a same issue of #20.

**Comment by kazegusuri** [comment]
closing because of duplicate issue.
