### ISSUE TITLE
Support multi process workers

### ISSUE THREAD

**Issue by alexlry** [fluent/fluent-plugin-prometheus#43]
Fluentd v0.14.12 introduced supports multi process workers.
This plugin isn't ready for multi process workers, so current workaround is to use <worker N> in configuration but this result in losing metrics from other workers.

Is there any plan to bring multi-process worker support to fluent-plugin-prometheus?

**Comment by sharon-vendrov** [comment]
@alexlry It seems that each worker has its own metrics, how do you scrape from one container multiple pods?

**Comment by alexlry** [comment]
@sharon-vendrov you are right, each worker has its own metrics.

I added an extra endpoint /metrics_all to retrieve metrics from all workers in this branch:
keymantics/fluent-plugin-prometheus@features/metrics_all_workers

If this fits your needs, I can create a new pull request.

**Comment by sharon-vendrov** [comment]
@alexlry PR will be GREAT! this is exactly what we need
Thank you

**Comment by dgonzalezruiz** [comment]
Could this issue be re-opened? Should we open a different one?

When using multi-worker options for fluentd, each of the workers bind to a different TCP port (incremental to the one specified in config), exposing different metrics. I.e. when setting 8991 for prometheus input port, worker0 will bind to 8991, worker1 to 8992...  

This is slightly misleading and unspecified in the documentation. Also, no labels respective to the scrapped worker are added to the metrics. 

This can be circumvented by enabling scrapes to said ports; as exported metrics are mainly counters, we can still do rates yielding true data, but it'd be great if this could be solved differently.

**Comment by repeatedly** [comment]
> This is slightly misleading and unspecified in the documentation.

https://github.com/fluent/fluent-plugin-prometheus#prometheus-input-plugin

> When using multiple workers, each worker binds to port + fluent_worker_id.

README mentions it

**Comment by alexlry** [comment]
I just created PR #109 to make it easier to fetch metrics from all workers.
