### ISSUE TITLE
prometheus_tail_monitor change position file pos

### ISSUE THREAD

**Issue by jl2005** [fluent/fluent-plugin-prometheus#49]
When I use `prometheus_tail_monitor`, I found that `Fluend` `pos_file` is incorrect. This is because  `prometheus_tail_monitor` will call `FilePositionEntry::read_inode` and `FilePositionEntry::read_pos` to modify the file pointer. When `Fluentd` is writing `pos_file`, it is possible to write to the wrong location. Related issues see [pos file error #1953](https://github.com/fluent/fluentd/issues/1953)

At the same time, `prometheus_tail_monitor` will also iterate `Fluentd` `tails` variable. When Fluentd is updated `tails`, it will cause `can't add a new key into hash during iteration`. Related issues see [can't add a new key into hash during iteration #1804](https://github.com/fluent/fluentd/issues/1804)

It is recommended to temporarily Disable `prometheus_tail_monitor` and add it when there is a better implementation.

**Comment by kazegusuri** [comment]
Thank you for filing an issue. I will check the detail.
BTW, I'm not sure why the plugin should be disabled. Is it enough to just stop using the plugin?

**Comment by kazegusuri** [comment]
Okay, I got the details. First one is a big bug and complicated, second one is easy to fix.
Both cases are caused by concurrent access to a value.

**Comment by kazegusuri** [comment]
I think this was fixed.
