### ISSUE TITLE
accessing kubernetes-matadata-plugin fields (nested fields)

### ISSUE THREAD

**Issue by mindw** [fluent/fluent-plugin-prometheus#53]
kubernetes metadata filter adds nested fields to records by default. These fields cannot be used for the `label` parameter.

FluentD added a helper API for plugins to solve this issue https://docs.fluentd.org/v1.0/articles/api-plugin-helper-record_accessor .

It will greatly ease creating custom metrics labels based on that metadata should labels gains nested field access.

Thanks!

**Comment by intenseFrog** [comment]
is there any update on this issue?

**Comment by alexfridlyand** [comment]
same issue

**Comment by repeatedly** [comment]
The author seems busy.
Does anyone write a patch?
Using `record_accessor` helps the problem.

**Comment by alexfridlyand** [comment]
Solved with workaround using record_transformer plugin by creating new label without nesting.
Not sure if i have time to take a look now also.

**Comment by alexfridlyand** [comment]
Trying to create PR, but Github doesn't allow me to (looks like a bug, i reload page couple of times and it appears back).
I closed first PR (failed base tests), then tried to create second one with new commits but it doesn't allow me.

Changes here: https://github.com/alexfridlyand/fluent-plugin-prometheus/tree/record_accessor_support

**Comment by alexfridlyand** [comment]
![image](https://user-images.githubusercontent.com/1177407/47297102-da052a00-d61c-11e8-82ea-30c675d30e5c.png)
keeps disappearing

**Comment by alexfridlyand** [comment]
When Github will stabilize, can someone take a look at my PR?
![image](https://user-images.githubusercontent.com/1177407/47297298-57c93580-d61d-11e8-92a2-30f5dd6a0bf1.png)

**Comment by alexfridlyand** [comment]
hello, can someone take a look at my PR? (#64)

**Comment by alexfridlyand** [comment]
#64 just merged, so we should probably close this issue

**Comment by repeatedly** [comment]
Release v1.2.0 for this feature. Thanks!
