### ISSUE TITLE
How to reset values?

### ISSUE THREAD

**Issue by wzrdtales** [fluent/fluent-plugin-prometheus#61]
I currently tried to figure out how to make this plugin reset its values. The assumption is that after a certain amount of time values become invalid and they should just reset to 0. This does however do not happen and therefor this plugin in combination with other plugins such as grepcounter are pretty much broken, since they can't actually monitor the real world values.

Is this something in the scope of this plugin, or don't you plan to support this at all?

**Comment by kazegusuri** [comment]
duplicated: https://github.com/fluent/fluent-plugin-prometheus/issues/20
