### ISSUE TITLE
Version update needed for multi workers support?

### ISSUE THREAD

**Issue by jstaffans** [fluent/fluent-plugin-prometheus#93]
I seem to be unable to use this plugin with Fluentd 1.4.2 running with multiple workers. I assume the fix from https://github.com/fluent/fluent-plugin-prometheus/commit/f15d2c41bb6d1afc1bf482ec17f2fdc458bf3da7 is needed. Would it be possible to release a new version?

**Comment by repeatedly** [comment]
@kazegusuri How about this?

**Comment by kazegusuri** [comment]
I have released the new version of fluent-plugin-prometheus! Please try it.

**Comment by jstaffans** [comment]
Yep, works great. Thanks!
